### PR TITLE
using newer google client and api

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by djay** [comment]
fixes #39

**Comment by cdw9** [comment]
Thanks for the work, Dylan! But I am curious as to why you used version 3 of the API, when version 4 is the latest?

**Comment by djay** [comment]
@cdw9 the management api was the one that was broken and the latest for that is v3. https://developers.google.com/analytics/devguides/reporting/core/v4. 

> The Analytics Reporting API v4 is separate from other v3 APIs (e.g., Management API, Metadata API, etc.) and requires a separate client library.

Was enough learning to get that working.

**Comment by djay** [comment]
@cdw9 if you could do some testing it would be good. I don't really use the reporting. I suspect its not working properly for some of the reports.

**Comment by cdw9** [comment]
We have one client that uses the portlet, I'll pass this on to them for testing

**Comment by djay** [comment]
@cdw9 ok, I just tried the v4 reporting api. We'd need to tell everyone to enable it which seems like too much work for now.

>  "message": "Analytics Reporting API has not been used in project 798384805741 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analyticsreporting.googleapis.com/overview?project=798384805741 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
>     "status": "PERMISSION_DENIED",

**Comment by djay** [comment]
@tomgross if you remember the code I'd appreciate the review otherwise I'll just merge.
Is there any better support in tag manager plugins to handle tracking of downloads?

**Comment by djay** [comment]
@cdw9 I'm probably going to merge this since I don't think anyone will review it. Any objections?

**Comment by cdw9** [comment]
I say go for it. If our client gets back to it, we can submit PRs if needed.  Thank you for your work!

**Pull request merged**
