### PR TITLE
Oauth2

### PR DESCRIPTION
**Pull request by frapell**
The old https://developers.google.com/accounts/docs/AuthSub is now deprecated. This branch replaces that authentication mechanism with the new supported OAuth2.

### CODE REVIEW

**Comment by tcurvelo** [comment]
AuthSub were discontinued in April 20th, 2015 :(  Can we have this yet?

**Comment by davisagli** [comment]
@tcurvelo you're welcome to review and merge it. The original authors of collective.googleanalytics are not using it these days.

**Comment by frapell** [comment]
FWIW, we are currently using this branch, and is working fine. But yeah, please review it and marge!

**Comment by yulmiro** [comment]
when this version (1.5)  will be available ?

**Comment by hvelarde** [comment]
@frapell please don't merge the implementation of new features or the fix of bugs in the same branch with code analysis stuff, as that makes the life of the person doing code review difficult.

**Pull request merged**
